--- 
title: "A Minimal Book Example"
author: "Lele Shu"
date: "`r Sys.Date()`"
output: pdf_document
description: This is a minimal example of using the bookdown package to write a book.
  The output format for this example is bookdown::gitbook.
documentclass: book
link-citations: yes
bibliography:
- book.bib
- packages.bib
site: bookdown::bookdown_site
biblio-style: apalike
---

# Overview

Penn State Integrated Hydrologic Model (MM-PIHM) is a spatially-distributed, physically-based hydrologic model. PIHM++ is the latest version of PIHM, re-developed in C++. 

PIHM++ is open source software and the development is coordinated via the PIHM GitHub page (\url{https://github.com/shulele/PIHM++}).

Penn State University makes no proprietary claims, either statutory or otherwise, to this version and release of MM-PIHM and considers MM-PIHM to be in the public domain for use by any person or entity for any purpose without any fee or charge.

We request that any PIHM user include a credit to Penn State in any publications that result from the use of PIHM.

The names Penn State shall not be used or referenced in any advertising or publicity which endorses or promotes any products or commercial entity associated with or using PIHM, or any derivative works thereof, without the written authorization of Penn State.

PIHM is provided on an ``AS IS`` basis and any warranties, either express or implied, including but not limited to implied warranties of noninfringement, originality, merchantability and fitness for a particular purpose, are disclaimed.

Penn State will not be obligated to provide the user with any support, consulting, training or assistance of any kind with regard to the use, operation and performance of PIHM nor to provide the user with any updates, revisions, new versions, error corrections or ``bug" fixes.

In no event will Penn State be liable for any damages, whatsoever, whether direct, indirect, consequential or special, which may result from an action in contract, negligence or other claim that arises out of or in connection with the access, use or performance of PIHM, including infringement actions.
